controller_frequency: 5.0
recovery_behaviour_enabled: true

TebLocalPlannerROS:
  
  # Robot Configuration Parameters
  max_vel_x: 20.0
  max_vel_x_backwards: 1.0
  max_vel_theta: 3.2
  acc_lim_x: 9.51
  acc_lim_theta: 10.0
  weight_kinematics_forward_drive: 1000
  
  acc_lim_x: 9.51
  acc_lim_y: 0.0
  acc_lim_trans: 9.51
  acc_lim_th: 3.2

  holonomic_robot: false
  sim_time: 3

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  meter_scoring: true
  free_goal_vel: true
  
  # Trajectory Parameters
  
  dt_ref: 0.1
  dt_hysteresis: 0.01
  min_samples: 10
  feasibility_check_no_poses: 16
  max_global_plan_lookahead_dist: 10
  min_obstacle_dist: 0.2
  weight_max_vel_x: 1000
  weight_acc_lim_x: 2

  
  # Obstacles Paramaters
  
#inflation_dist: 1.0
#min_obstacle_dist
