local_costmap:
  global_frame: /odom
  static_map: false
  rolling_window: true
  width: 100
  height: 100
  update_frequency: 5.0
  publish_frequency: 10.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
